# == Global project settings ===========================================

name:             OSM Elemental
description:      ''
attribution:      'Map Data © OpenStreetMap'
bounds:           [-180.0, -85.0511, 180.0, 85.0511]
center:           [0, 20, 3]
format:           png
interactivity:    false
minzoom:          0
maxzoom:          20
srs:              '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'


# == Layer & Datasource defaults =======================================

_layer_default:   &layer
  'srs-name':     '900913'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

_pg_default:      &postgis
  type:           postgis
  dbname:         osm2pgsql
  host:           localhost
  user:           postgres
  geometry_field: way
  extent:         '-20037508.34, -20037508.34, 20037508.34, 20037508.34'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'


# == Stylesheets =======================================================

Stylesheet:
  - mss/map.mss
  - mss/park.mss
  - mss/water.mss
  - mss/road.mss


# == Layers ============================================================

Layer:

  # ---- Landuse / landcover areas -------------------------------------

  - <<: *layer
    name: park
    id:   park
    Datasource:
      <<: *postgis
      table: >
        ( select way from planet_osm_polygon
          where tags->'leisure' in (
            'park',
            'common',
            'playground',
            'village_green')
        ) as x

  # ---- Water ---------------------------------------------------------

  - <<: *layer
    name: ocean_ne
    id:   ocean_ne
    Datasource:
      file: layers/10m_ocean.shp

  - <<: *layer
    name: ocean
    id:   ocean
    Datasource:
      file: layers/water_polygons.shp

  - <<: *layer
    name: water
    id:   water
    Datasource:
      <<: *postgis
      table: >
        ( select way from planet_osm_polygon
          where tags->'natural' = 'water'
            or tags->'waterway' in ('riverbank', 'dock')
            or tags->'landuse' = 'reservoir'
        ) as x

  # ---- Roads ---------------------------------------------------------

  - <<: *layer
    name: road
    id:   road
    Datasource:
      <<: *postgis
      table: >
        ( select way, case
            when tags->'highway' in ('living_street', 'pedestrian') then 5
            when tags->'highway' in ('secondary_link', 'tertiary_link',
              'unclassified', 'residential', 'road') then 4
            when tags->'highway' in ('secondary', 'tertiary',
              'trunk_link', 'primary_link') then 3
            when tags->'highway' in ('trunk', 'primary', 'motorway_link') then 2
            when tags->'highway' = 'motorway' then 1
            else null end as class
          from planet_osm_line
          where tags ? 'highway'
        ) as x

