# == Global project settings ===========================================

name:             GGNPC Background
description:      ''
attribution:      'Map Data © OpenStreetMap'
bounds:           [-123.640, 36.791, -121.025, 38.719]
center:           [-122.5369, 37.8704, 13]
format:           png
interactivity:    false
minzoom:          10
maxzoom:          20
srs:              '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'
metatile:         2


# == Layer & Datasource defaults =======================================

_layer_default:   &layer
  'srs-name':     '900913'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

_pg_default:      &postgis
  type:           postgis
  dbname:         {{dbname}}
  host:           {{dbhost}}
  user:           {{dbuser}}
  password:       {{dbpassword}}
  port:           {{dbport}}
  geometry_field: way
  extent:         '-13763541.8416803, 4410014.78335954, -13472441.3732559, 4681500.2899002'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'


# == Stylesheets =======================================================

Stylesheet:
  - map.mss
  - roads.mss
  - icons.mss
  - labels.mss


# == Layers ============================================================

Layer:

  # ---- Land areas ----------------------------------------------------

  - <<: *layer
    name: land
    id:   land
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT !bbox! geom
        ) AS _

  # ---- Protected Areas (CPAD) ----------------------------------------

  - <<: *layer
    name: cpad_units
    id:   cpad_units
    status: on
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT access_typ AS access_type, geom
          FROM cpad_units
          WHERE geom && !bbox!
        ) AS _

  # ---- GGNRA Boundary ------------------------------------------------

  - <<: *layer
    name: park_units
    id:   park_units
    status: on
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT goga_man, geom
          FROM park_units
          WHERE geom && !bbox!
            AND goga_man IN ('Yes', 'Trust', 'Offshore')
        ) AS _

  # ---- School (OSM) --------------------------------------------------

  - <<: *layer
    name: school
    id:   school
    status: on
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT way
          FROM planet_osm_polygon
          WHERE way && !bbox!
            AND tags @> 'amenity=>university'
        ) AS school

  # ---- Foreshore (NHD) -----------------------------------------------

  - <<: *layer
    name: foreshore
    id:   foreshore
    status: on
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
            SELECT ftype, ST_Collect(geom) AS geom
            FROM nhdarea
            WHERE geom && !bbox!
              AND fcode IN (
                36400, -- Foreshore

                 -1
              )
            GROUP BY ftype
        ) AS _

    # ---- Beach (OSM) ---------------------------------------------------

  - <<: *layer
    name: beach
    id:   beach
    status: on
    Datasource:
      <<: *postgis
      table: >
        (
            SELECT way
            FROM planet_osm_polygon
            WHERE way && !bbox!
              AND tags @> 'natural=>beach'
        ) AS beach

  # ---- Sports Fields -------------------------------------------------

  - <<: *layer
    name: fields
    id:   fields
    status: on
    properties:
      minzoom: 14
    Datasource:
      <<: *postgis
      table: >
        (
        SELECT tags -> 'leisure' leisure, way
        FROM planet_osm_polygon
        WHERE way && !bbox!
        AND tags ? 'leisure'
        AND tags -> 'leisure' IN ('pitch', 'playground', 'stadium', 'recreation_ground', 'court', 'tennis', 'track', 'dog_park', 'golf_course')
        ) AS _

  # ---- Parking Areas -------------------------------------------------

  - <<: *layer
    name: parking
    id:   parking
    status: on
    properties:
      minzoom: 15
    Datasource:
      <<: *postgis
      geometry_field: geom
      table: >
        (
          SELECT ST_Union(geom) geom
          FROM (
            SELECT geom
            FROM ggnra_parking_areas
            WHERE geom && !bbox!
          UNION
            SELECT geom
            FROM pt_parking_areas
            WHERE geom && !bbox!
          ) AS _
        ) AS _

